### PR TITLE
Add deployment ARM templates

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Still to do

- [x] Create BLOB containers 'ods-input' and 'ods-split'
- [x] Investigate occasional deployment failures - I think this is probably due to missing dependency entries for resources.
- [x] Tag resources using git repo & branch details
- [x] Populate DocumentDB connection string.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
Problems at the testing stage ...

The functions assume BLOB containers called ods-input and ods-split but it seems it is not possible to create these using ARM templates.

This is a Twitter exchange with Marcus at Microsoft

> (Me) This SO post seems to suggest that it is not possible to create Blob containers using ARM templates http://stackoverflow.com/questions/41004779/create-azure-blob-fileshare-container-through-arm-template Just wanted to check that is that correct as far as you know?

> (Me) I've got a nice ARM template for the deployment of an Azure Function. It works well in terms of deployment but the functions assume the presence of a named blob container and the SO post implies I can't create them using templates.

> (Marcus) Yes, it is frustrating. I've hit the hurdle a few times. Apparently containers are part of the data plane, not resources hence it can't be done in an ARM template. It could be pre provisioned using the CLI: azure storage container create <containername> -a <storageaccountname> -k <storageaccountkey> , at maybe created within the function if the container doesn't exist. I've not done a great deal with functions, but if can pass a account name and key key to it in the template that might be a good way forward. You can retrieve the key within the ARM template itself using listKeys.

> (Marcus) Hmm, although not sure if can create using the REST API and an access key. If still struggling let me know and will ask others.

> (Me) OK, thanks. Will use the CLI probably.

**Update** Did it through the CLI

**Comment by neilbmclaughlin** [comment]
[Create isolated development environments in Azure](https://trello.com/c/HMlO6Gv8/631-create-isolated-development-environments-in-azure)

**Comment by neilbmclaughlin** [comment]
The code as stands will create a stand-alone azure environment for the function app in a created resource group which is named by github org, repo, branch and user (e.g. nhsuk.service-etl-function-app.feature_add-deployment-scripts.neilmclaughlin).

The only manual intervention required is to set the indexing policy for the DocumentDB to include:

```
{
  "indexingMode": "consistent",
  "automatic": true,
  "includedPaths": [
    {
      "path": "/*",
      "indexes": [
        {
          "kind": "Range",
          "dataType": "Number",
          "precision": -1
        },
        {
          "kind": "Range",
          "dataType": "String",
          "precision": -1
        },
        {
          "kind": "Spatial",
          "dataType": "Point"
        }
      ]
    }
  ],
  "excludedPaths": []
}
```
This is required in order to execute spatial queries and, if not set, then an error will be thrown from the nearby services api when executing.

The final function step (D_TransformAndStore) has the option to auto create the DB. This should be disabled and the function itself take on responsibility for DB and Collection creation as well as index definition. In view of the possibility of a switch from DocumentDB to Mongo this has been left as a manual step for now.

**Comment by neilbmclaughlin** [comment]
It would be a small step to get build.sh script running as a GitHub webhook triggered on the pull-request open event which would automatically create an environment. The resource group name would then be modified to include the PR number.

**Comment by neilbmclaughlin** [comment]
Experimented with using an 'external' existing app service plan (see branch feature/use-common-plan).

Ran into problems whereby Azure cleaned up plans with no app services associated with them which added extra complexity to the script as you have to check a plan exists and that it is not being deleted. There is the potential for race conditions even with checking for existence.

Finally, because the function app is on a consumption plan it is only charged for usage and using a 'common' plan is of little value.

The sharing of storage locations is also of marginal benefit as the cost is in pennies per month, the limit of storage accounts per subscription is 250 and we would have to do some sort of transform on the code as the function definitions have the BLOB container names hard coded.

The sharing of DocumentDB instances is a possibility and will be investigated.

**Comment by neilbmclaughlin** [comment]
I've left this as WIP as I'd like to hear comments on the work so far.

I'll be looking at the nearby-service-api next to work on creating the ARM template and script for that and a 'master' template to allow service-etl-function-app and nearby-service-api to be deployed as a unit. See the scripts/master-template.json and [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-linked-templates) for more details on linked templates.

**Comment by st3v3nhunt** [comment]
@neilbmclaughlin Is this dead now we've moved to Docker?

**Comment by neilbmclaughlin** [comment]
Redundant now we have moved to docker

**Pull request closed without merging**
